language: scala
jdk:
  - openjdk8
scala:
  - 2.13.1
env:
  global:
    - secure: i7dwrB8WXAW8emKy0e4hMaWYAowqIXAEtpiwLL8Bx+OFvdnyAG3MV53Jc/dJ4jWuCTXZw9aPdueQ1du5DiZIwKDUMj+i0feAnYFAU/JKjvb0NAoOQDQFODQin47VSzp0nqHcjIW+OT3ljeQREr8j9ezQCLZdrLQAE742y6Os52cgFqE6iuw062oLplT3rPGIXhoeDKee2Ppfc/QJc9h6I6i87CFVFKCY2EYmDCMfFyJncc0BBZQLaFvBqMESCoDZbhNMbrcEVTU8yofDFjCrelZUHRG60k7v5mkaXEAUJApvDjLN5AY9FRccyCHMIvCV84tLFxRoodlurdmQgRHCuRD7vpUMPMpsZKpZ2assCAVjtrBL/DgH8GTfjXVFkuDSJDX5lLeKC9zvrVLtyQQShXdKycnAJwm6z+EJMjSo+1oiouC3y8zWFDPaRuQp6vzShlCpVWL1curnK9Np8R4dn1Mh/vbrEXY1szd4+cOXtz+sSQEL//a9oA/GGJnljHpheJ7pTkTxenem8O1j+7E2HZMcfoHApeeXBlVFDK9oeCPHWLsfSs7lPjab0lyU4XpYkB7NpYDpKuf4Yl27DpVsLqh0xL8m5EEN83nHwowmntrDWw/Oyxa5N3jaWNdbfNq6XoLcJOrh79OZT+2fE5KJ/Sigovpk3ICfz8wN7p0WmfM=
    - secure: fB1NMY9EmJKt1AeoqDs3LUzRc4ZCggLGXF4/7zsd9rdpqwxmsxjG8yvjyKCEOdjHcb4XLxdG8EI0+/q+HBp8qokmv6ns3kcbv4TWhVWNhcH7KG0AKg+wc+xlI/i/vdDgRFIF194KxWif9/Vhypr8T5LRudPycBdRq9sIorIiZap5xiS0OhhWmd20ZhNnlwCy+XedJWJpIhNEdVaUEGjd2nsWn90sCWRLN259wN5UM2a3+I4N4pTaI44q3wgwO3TGE343Ys/7LtNAuDhNZoEknAenkf4N2aplVgjAIQXd2FR5FjQ6ddGjojn1mJkznAsHdTuhcNurxsP6QaIqJqzM/55AORJDebLYuIdtm4dpy/czX5ijn1YPYDrVV3mWTYXnpvkCujxB0EX1tbJXrDIAeZsZrQaTQHC3CwzDOaM1L7oFhHcZv0y2ZgGTBWrmkgADhVTAJt7i/PJdxGfhgdFePqM85IfsiYcZeM9y+KxHtWJjaVKLbIRkkTVxtxWXZOhXZhu4LlAr8X/OuOoyQrm7GgRc51yLi3Cr4n+mma2PIcmZyVS4YG17BEGc2JNVfHgrxdv8th681ughHeyX4KzlP9zf61dDwEgbMbW6jvJ5Ngiquf0zzfFv47buEzLlgGgEh1igQKt5YWMz6M+0WBur2GGTwTwhlbBnX4n6XA2xqFc=
    - secure: TkJlaTT9jDgAVGW1fOA//ikj5ef4oIVC5XyX1HRbLqWBtNIkoQ72EKGNFM1pkntubtBVZXQZ70VSRvpvE/sEDQvYrOWfvqc3flD1KSFjr2LChCKXlr7jCWDsgD2ZsDRbc+yDJ8IPlNQ0egHhGCT44mTpG6x01ShAD4YVks/ZACU82DWVVV1XBFBTwV6vJshCanjbah9tvUwsCCNiqhvzEPtdfJgE7TmRNhmCC2VrYjf2/WL58c3ZXRZdR9gs9xJH3HdAL7rFFuCGlv/VOhcHnA40V8T5GTXd+ntUyZ6GRXIeRjTrXO/Tyvc9lPBuNZRJaDPguoz//HvOZ7EEZnkHcVyQo9CQplnaOqnoGWL3NxJb5nNjajGbCCrkCQW2cZM/vwxK1Pul5d9ZP4Q5KmzNVF8EKNmmfAke6hjNCAmdYfSc6J0nT/U9dUh/hERcCY4FfxXKDKX7QYFA6DMOKYIHP5MuKFFFMgJ0bliXKtUWQUS8MlUyDb16EQYNSibZLTz8Z8Amq6JH+w3vZy4/gnjnFSaKI8QGuOWToxFqzgMyvN+NOvNYfNyPCapqyKRi9gp0qYBAC04XX0kdSp+8dfsOgBhHdZ0zqbj5ch8jVCQpKqXpSA1LQ7DtEBrRTpBW83/E6iXi7DAdwJiKQfVKCdaHBdk2Ql7cFcxWhzoKlZwkuuE=
    - secure: a+DTlHeCs11UfzU8RS12XLLV5Je2eQM1ia/XGJSa7okwe7w0e6laFEi9pYrNw/WknoSyXTkE8q8V4BVE6zkpVV2gFWwi9wpm+Jgb02RaeNh4CEeTPTvJoYabkJV1CvPg2xqTOueHgEDfQzBvk86nG5WW1JS0IC97xoL53wk+YIVm7ohdYt1ZtCDnz0ak82olujV2ufui0NK62AxlEpICD4y21KRPUrL/3tMJwN2BCB1nD5uj1lWDkbKr5ghltjw/dqy9Ww+94fruORn6JCqVc9/VebYqsQARmBE5gIYpwVh3h1eF2WT9odbK3M6nxwicm1mPU1ya2mp67WxGS4oMJsa9ue0avZibZ7DUybS3DLcKH5bAhcp6ieUbdLYK7ac5YlzZ5wGjaxrO0Bx6ixGu8LIhdrYwk+3xpLOw0w94M3VA2zGba2iymV/ASDFjOJF2GOnW+kR01qtO6btQwUYaIUdEWHE6JIC7cNnLolInVHAyEWASv2DRCNwEtqoK/d5Hcz2ShP3P45BcwpuLo9ZBTP8yrsARgtgmuAhxW1nyPg2CFaEObTrrRRt07vYlyZ6iJGuL3kI97bIcyNOeTLxRpFz10Xcoox1r9sXn5PUov1moF9fJIWzGtjEBt4YJeNkpSodfnWchsYzFNmgb6ZSb8ksLMu9rIY+5j0ACG3DcQ54=
before_install:
  - |
    if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      openssl aes-256-cbc \
        -K $encrypted_6987e22a53f0_key \
        -iv $encrypted_6987e22a53f0_iv \
        -in travis/secrets.tar.enc \
        -out travis/secrets.tar -d;
      tar xv -C travis -f travis/secrets.tar;
    fi
script:
  - sbt ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - |
    if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      sbt release
    fi
cache:
  directories:
    - "$HOME/.sbt/1.0"
    - "$HOME/.sbt/boot/scala*"
    - "$HOME/.sbt/cache"
    - "$HOME/.sbt/launchers"
    - "$HOME/.ivy2"
before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
